In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\Dell'

In [5]:
os.listdir()

['.anaconda',
 '.bash_history',
 '.conda',
 '.condarc',
 '.continuum',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.matplotlib',
 '.nuget',
 '.p2',
 '.spyder-py3',
 '.streamlit',
 '.templateengine',
 '.virtual_documents',
 '3D Objects',
 'AI_data_',
 'anaconda3',
 'AppData',
 'Application Data',
 'archive (2)(1)',
 'archive (2)(1).zip',
 'archive (3)',
 'Contacts',
 'Cookies',
 'customer_shopping_analysis',
 'Customer_Shopping_Analysis.ipynb',
 'customer_shopping_cleaned.csv',
 'data_employees.csv',
 'Documents',
 'Downloads',
 'ecommerce_sales.ipynb',
 'ecommerce_sales_34500.ipynb',
 'Favorites',
 'github',
 'Links',
 'Local Settings',
 'Microsoft',
 'Monthly_Sales_Data.csv',
 'Multi-touch-marketing-Roi-dashboard',
 'multi_touch_attribution_data.csv',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{8fbb2d4e-b2ee-11ef-a2a9-a145de5c2f02}.TM.blf',
 'NTUSER.DAT{8fbb2d4e-b2ee-11ef-a2a9-a145de5c2f02}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{8fbb2d4e-b2ee-11ef-a2a9-a145de5c2f02}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'SaaS-Ecommerce Cohort Retebtion & CLTV Analysis',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos',
 'Week1_EDA1.ipynb.ipynb',
 'WPS Cloud Files']

In [5]:
# Example if it's in your Downloads folder:
df = pd.read_csv(r"C:\Users\Dell\online_retail_II.csv")

In [6]:
df.head

<bound method NDFrame.head of         Invoice StockCode                          Description  Quantity  \
0        489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434    79323P                   PINK CHERRY LIGHTS        12
2        489434    79323W                  WHITE CHERRY LIGHTS        12
3        489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4        489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...       ...                                  ...       ...
1067366  581587     22899         CHILDREN'S APRON DOLLY GIRL          6
1067367  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
1067368  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
1067369  581587     22138        BAKING SET 9 PIECE RETROSPOT          3
1067370  581587      POST                              POSTAGE         1

                 InvoiceDate  Price  Customer ID         Country
0        2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3        2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4        2009-12-01 07:45:00   1.25      13085.0  United Kingdom
...                      ...    ...          ...             ...
1067366  2011-12-09 12:50:00   2.10      12680.0          France
1067367  2011-12-09 12:50:00   4.15      12680.0          France
1067368  2011-12-09 12:50:00   4.15      12680.0          France
1067369  2011-12-09 12:50:00   4.95      12680.0          France
1067370  2011-12-09 12:50:00  18.00      12680.0          France

[1067371 rows x 8 columns]>

In [9]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [10]:
df.shape

(1067371, 8)

In [14]:
print(df.columns)

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [17]:
#Missing Values Analysis
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [18]:
missing = (df.isnull().sum()/len(df))*100

missing.sort_values(ascending=False)

Customer ID    22.766873
Description     0.410541
Invoice         0.000000
StockCode       0.000000
Quantity        0.000000
InvoiceDate     0.000000
Price           0.000000
Country         0.000000
dtype: float64

In [19]:
#Remove Invalid Customer Records

In [20]:
df = df.dropna(subset=['Customer ID'])

In [21]:
df.shape

(824364, 8)

In [22]:
#Remove Cancelled Orders

In [23]:
df[df['Invoice'].astype(str).str.startswith('C')].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [24]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

In [27]:
df.shape

(805620, 8)

In [28]:
#Remove Negative Quantity
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [29]:
df = df[df['Quantity'] > 0]

In [31]:
#Remove Negative Price
df = df[df['Price'] > 0]

In [32]:
df[['Quantity','Price']].describe()

            Quantity          Price
count  805549.000000  805549.000000
mean       13.290522       3.206561
std       143.634088      29.199173
min         1.000000       0.001000
25%         2.000000       1.250000
50%         5.000000       1.950000
75%        12.000000       3.750000
max     80995.000000   10953.500000

In [50]:
#Remove Duplicates
df.duplicated().sum()

0

In [26]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [27]:
#Convert Date Format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 11 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Invoice       1033036 non-null  object
 1   StockCode     1033036 non-null  object
 2   Description   1028761 non-null  object
 3   Quantity      1033036 non-null  int64
 4   InvoiceDate   1033036 non-null  datetime64[ns]
 5   Price         1033036 non-null  float64
 6   Customer ID   797885 non-null   float64
 7   Country       1033036 non-null  object
 8   Revenue       1033036 non-null  float64
 9   InvoiceMonth  1033036 non-null  period[M]
 10  CohortMonth   797885 non-null   period[M]
dtypes: datetime64[ns](1), float64(3), int64(1), object(4), period[M](2)
memory usage: 94.6+ MB

In [29]:
timestamp = np.datetime64('2026-07-07', 'ns')

In [30]:
#Create Revenue Column
df['Revenue'] = df['Quantity'] * df['Price']
df[['Quantity','Price','Revenue']].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

In [31]:
#Create Purchase Month
# 1. Force Pandas to create a completely independent copy of the data
df = df.copy()

# 2. Ensure date format is correct
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# 3. Create the InvoiceMonth column
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

# 4. Create the CohortMonth column
cohort = df.groupby('Customer ID')['InvoiceMonth'].min()
df['CohortMonth'] = df['Customer ID'].map(cohort)

In [32]:
df[['Customer ID','InvoiceMonth','CohortMonth']].head()

   Customer ID InvoiceMonth CohortMonth
0      13085.0      2009-12     2009-12
1      13085.0      2009-12     2009-12
2      13085.0      2009-12     2009-12
3      13085.0      2009-12     2009-12
4      13085.0      2009-12     2009-12

In [51]:
df = df.drop_duplicates()

df = df.dropna(
    subset=['InvoiceDate','Customer ID','Quantity','Price']
)

In [53]:
df.shape

(779425, 11)

In [2]:
# Ensure raw_df and df are defined before running this
if 'raw_df' in locals() and 'df' in locals():
    raw_rows = len(raw_df)
    clean_rows = len(df)

    removed = raw_rows - clean_rows
    retention = (clean_rows / raw_rows) * 100 if raw_rows > 0 else 0

    print(f"Removed Rows: {removed}")
    print(f"Retention %: {round(retention, 2)}%")
else:
    print("Error: Ensure both 'raw_df' and 'df' are defined.")

Error: Ensure both 'raw_df' and 'df' are defined.

In [36]:
df[df['InvoiceDate'].isna()]
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12,2011-08
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12,2011-08
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011-12,2011-08

In [41]:
df.shape
df['Revenue'] = df['Quantity'] * df['Price']

In [42]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [43]:
df['CohortMonth'] = (
    df.groupby('Customer ID')['InvoiceDate']
      .transform('min')
      .dt.to_period('M')
)

In [44]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12,2011-08
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12,2011-08
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011-12,2011-08

In [54]:
print(df.head())
print(df.shape)

  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

          InvoiceDate  Price  Customer ID         Country  Revenue  \
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom     83.4
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom    100.8
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom     30.0

  InvoiceMonth CohortMonth
0      2009-12     2009-12
1      2009-12     2009-12
2      2009-12     2009-12
3      2009-12     2009-12
4      2009-12     2009-12
(779425, 11)

In [55]:
#change type
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')

#remove negative
df = df[(df['Quantity'] > 0) & (df['Price'] > 0)]

# file saved
df.to_csv('online_retail_final_cleaned.csv', sep='|')
print("File saved successfully")

File saved successfully

In [57]:
df.shape

(779425, 11)