In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\Dell\\SaaS-Ecommerce Cohort Retebtion & CLTV Analysis\\Notebook\\week1'

In [4]:
import os

for file in os.listdir():
    print(file)

.ipynb_checkpoints
online_retail_final_v2.csv
week 1.ipynb
week 1SaaS-Ecommerce Cohort.ipynb

In [5]:
#df = pd.read_csv("online_retail_II.csv")


df = pd.read_csv(r"C:\Users\Dell\online_retail_II.csv")

In [6]:
df.head

<bound method NDFrame.head of         Invoice StockCode                          Description  Quantity  \
0        489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434    79323P                   PINK CHERRY LIGHTS        12
2        489434    79323W                  WHITE CHERRY LIGHTS        12
3        489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4        489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...       ...                                  ...       ...
1067366  581587     22899         CHILDREN'S APRON DOLLY GIRL          6
1067367  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
1067368  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
1067369  581587     22138        BAKING SET 9 PIECE RETROSPOT          3
1067370  581587      POST                              POSTAGE         1

                 InvoiceDate  Price  Customer ID         Country
0        2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3        2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4        2009-12-01 07:45:00   1.25      13085.0  United Kingdom
...                      ...    ...          ...             ...
1067366  2011-12-09 12:50:00   2.10      12680.0          France
1067367  2011-12-09 12:50:00   4.15      12680.0          France
1067368  2011-12-09 12:50:00   4.15      12680.0          France
1067369  2011-12-09 12:50:00   4.95      12680.0          France
1067370  2011-12-09 12:50:00  18.00      12680.0          France

[1067371 rows x 8 columns]>

In [7]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.shape

(1067371, 8)

In [9]:
print(df.columns)

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [11]:
#Missing Values Analysis
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [12]:
missing = (df.isnull().sum()/len(df))*100

missing.sort_values(ascending=False)

Customer ID    22.766873
Description     0.410541
Invoice         0.000000
StockCode       0.000000
Quantity        0.000000
InvoiceDate     0.000000
Price           0.000000
Country         0.000000
dtype: float64

In [13]:
#Remove Invalid Customer Records

In [14]:
df = df.dropna(subset=['Customer ID'])

In [15]:
df.shape

(824364, 8)

In [16]:
#Remove Cancelled Orders

In [17]:
df[df['Invoice'].astype(str).str.startswith('C')].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [18]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

In [19]:
df.shape

(805620, 8)

In [20]:
#Remove Negative Quantity
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [21]:
df = df[df['Quantity'] > 0]

In [22]:
#Remove Negative Price
df = df[df['Price'] > 0]

In [23]:
df[['Quantity','Price']].describe()

            Quantity          Price
count  805549.000000  805549.000000
mean       13.290522       3.206561
std       143.634088      29.199173
min         1.000000       0.001000
25%         2.000000       1.250000
50%         5.000000       1.950000
75%        12.000000       3.750000
max     80995.000000   10953.500000

In [24]:
#Remove Duplicates
df.duplicated().sum()

26124

In [25]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [26]:
#Convert Date Format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 53.5+ MB

In [28]:
timestamp = np.datetime64('2026-07-07', 'ns')

In [29]:
#Create Revenue Column
df['Revenue'] = df['Quantity'] * df['Price']
df[['Quantity','Price','Revenue']].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

In [30]:
#Create Purchase Month
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')
df[['InvoiceDate','InvoiceMonth']].head()

          InvoiceDate InvoiceMonth
0 2009-12-01 07:45:00      2009-12
1 2009-12-01 07:45:00      2009-12
2 2009-12-01 07:45:00      2009-12
3 2009-12-01 07:45:00      2009-12
4 2009-12-01 07:45:00      2009-12

In [31]:
#Create Cohort Month
cohort = df.groupby('Customer ID')['InvoiceMonth'].min()
df['CohortMonth'] = df['Customer ID'].map(cohort)

In [1]:
df[['Customer ID','InvoiceMonth','CohortMonth']].head()

NameError: name 'df' is not defined

In [33]:
df.to_csv(
    "online_retail_cleaned.csv",
    index=False
)
print ("successfully file saved")

successfully file saved

In [34]:
# Ensure raw_df and df are defined before running this
if 'raw_df' in locals() and 'df' in locals():
    raw_rows = len(raw_df)
    clean_rows = len(df)

    removed = raw_rows - clean_rows
    retention = (clean_rows / raw_rows) * 100 if raw_rows > 0 else 0

    print(f"Removed Rows: {removed}")
    print(f"Retention %: {round(retention, 2)}%")
else:
    print("Error: Ensure both 'raw_df' and 'df' are defined.")

Error: Ensure both 'raw_df' and 'df' are defined.

In [35]:
df = df.drop_duplicates()

df = df.dropna(
    subset=['InvoiceDate','Customer ID','Quantity','Price']
)

In [36]:
df[df['InvoiceDate'].isna()]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Revenue, InvoiceMonth, CohortMonth]
Index: []

In [37]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12,2011-08
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12,2011-08
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011-12,2011-08

In [38]:
df.shape

(779425, 11)

In [39]:
df.to_csv('online_retail_final_cleaned.csv', index=False)
print ("successfull")

successfull

In [40]:
import os
print(os.getcwd())

C:\Users\Dell\SaaS-Ecommerce Cohort Retebtion & CLTV Analysis\Notebook\week1

In [41]:
df['Revenue'] = df['Quantity'] * df['Price']

In [42]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [43]:
df['CohortMonth'] = (
    df.groupby('Customer ID')['InvoiceDate']
      .transform('min')
      .dt.to_period('M')
)

In [44]:
df.to_csv('online_retail_cohort_ready.csv', index=False) 
print("sucessfully saved")

sucessfully saved

In [45]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12,2011-08
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12,2011-08
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12,2011-08
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011-12,2011-08

In [46]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009-12,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009-12,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009-12,2009-12

In [47]:


print(df.head())
print(df.shape)

  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

          InvoiceDate  Price  Customer ID         Country  Revenue  \
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom     83.4
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom    100.8
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom     30.0

  InvoiceMonth CohortMonth
0      2009-12     2009-12
1      2009-12     2009-12
2      2009-12     2009-12
3      2009-12     2009-12
4      2009-12     2009-12
(779425, 11)

In [48]:
df = pd.read_csv("online_retail_cohort_ready.csv")

print(df.head())
print(df.shape)

   Invoice StockCode                          Description  Quantity  \
0   489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1   489434    79323P                   PINK CHERRY LIGHTS        12
2   489434    79323W                  WHITE CHERRY LIGHTS        12
3   489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4   489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

           InvoiceDate  Price  Customer ID         Country  Revenue  \
0  2009-12-01 07:45:00   6.95      13085.0  United Kingdom     83.4
1  2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
2  2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
3  2009-12-01 07:45:00   2.10      13085.0  United Kingdom    100.8
4  2009-12-01 07:45:00   1.25      13085.0  United Kingdom     30.0

  InvoiceMonth CohortMonth
0      2009-12     2009-12
1      2009-12     2009-12
2      2009-12     2009-12
3      2009-12     2009-12
4      2009-12     2009-12
(779425, 11)

In [49]:

print(df.shape)
print(df.head())
print(df.columns)

(779425, 11)
   Invoice StockCode                          Description  Quantity  \
0   489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1   489434    79323P                   PINK CHERRY LIGHTS        12
2   489434    79323W                  WHITE CHERRY LIGHTS        12
3   489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4   489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

           InvoiceDate  Price  Customer ID         Country  Revenue  \
0  2009-12-01 07:45:00   6.95      13085.0  United Kingdom     83.4
1  2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
2  2009-12-01 07:45:00   6.75      13085.0  United Kingdom     81.0
3  2009-12-01 07:45:00   2.10      13085.0  United Kingdom    100.8
4  2009-12-01 07:45:00   1.25      13085.0  United Kingdom     30.0

  InvoiceMonth CohortMonth
0      2009-12     2009-12
1      2009-12     2009-12
2      2009-12     2009-12
3      2009-12     2009-12
4      2009-12     2009-12
Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'Revenue', 'InvoiceMonth',
       'CohortMonth'],
      dtype='object')

In [50]:
df.shape

(779425, 11)

In [ ]:

df.replace(to_replace=[r'"', "'"], value='', regex=True, inplace=True)


df.to_csv('online_retail_final_v2.csv', index=False, sep='|')
print("file,'online_retail_final_v2.csv'saved")

In [58]:
import pandas as pd
df = pd.read_csv('online_retail_sql.csv', low_memory=False)

#change type
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')

#remove negative
df = df[(df['Quantity'] > 0) & (df['Price'] > 0)]

# file saved
df.to_csv('online_retail_final_cleaned.csv', index=False, sep='|')
print("File saved successfully")

FileNotFoundError: [Errno 2] No such file or directory: 'online_retail_sql.csv'