##week1_EDA.ipynb

In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Load Dataset
df = pd.read_csv(r"C:\Users\Dell\Multi-touch-marketing-Roi-dashboard\multi_touch_attribution_data.csv")

In [4]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [6]:
df.shape

(10000, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  object
 2   Channel     10000 non-null  object
 3   Campaign    10000 non-null  object
 4   Conversion  10000 non-null  object
dtypes: int64(1), object(4)
memory usage: 390.8+ KB

In [8]:
df.describe()

           User ID
count  10000.00000
mean   54957.01700
std    25685.14741
min    10028.00000
25%    32391.00000
50%    55446.00000
75%    77298.00000
max    99995.00000

In [9]:
#Detect null values
df.isnull().sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [10]:
(df.isnull().sum() / len(df)) * 100

User ID       0.0
Timestamp     0.0
Channel       0.0
Campaign      0.0
Conversion    0.0
dtype: float64

In [11]:
for col in df.columns:
    print(col, df[col].unique()[:10])

User ID [83281 68071 90131 71026 94486 31134 99995 45832 79863 35324]
Timestamp ['2025-02-10 07:58:51' '2025-02-10 23:38:48' '2025-02-11 10:41:07'
 '2025-02-10 08:19:44' '2025-02-10 15:15:46' '2025-02-11 06:43:06'
 '2025-02-10 06:15:30' '2025-02-11 01:09:27' '2025-02-10 06:48:56'
 '2025-02-10 21:36:24']
Channel ['Email' 'Search Ads' 'Social Media' 'Direct Traffic' 'Referral'
 'Display Ads']
Campaign ['New Product Launch' 'Winter Sale' 'Brand Awareness' '-' 'Retargeting'
 'Discount Offer']
Conversion ['No' 'Yes']

In [ ]:
(df == "").sum()

In [12]:
(df == " ").sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [18]:
df['User ID'].value_counts().head(10)

User ID
13186    12
53526    12
86889    12
37332    11
48099    11
46988    11
58496    10
29809    10
10654    10
73105    10
Name: count, dtype: int64

In [19]:
#remove duplicates
df.duplicated().sum()

0

In [40]:
df_cleaned = df.drop_duplicates()

In [22]:
df.shape

(10000, 5)

In [24]:
#Validate
df_cleaned.shape
df.shape

(10000, 5)

In [26]:
#User journey length
df.groupby('User ID').size().describe()

count    2847.000000
mean        3.512469
std         1.770702
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        12.000000
dtype: float64

In [28]:
#Top users by interactions
df['User ID'].value_counts().head(10)

User ID
13186    12
53526    12
86889    12
37332    11
48099    11
46988    11
58496    10
29809    10
10654    10
73105    10
Name: count, dtype: int64

In [29]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [30]:
df.groupby('User ID').size().sort_values(ascending=False).head(10)

User ID
86889    12
13186    12
53526    12
48099    11
37332    11
46988    11
73105    10
29809    10
10654    10
58496    10
dtype: int64

In [31]:
#Check conversion distribution:
df['Conversion'].value_counts()

Conversion
No     5056
Yes    4944
Name: count, dtype: int64

In [33]:
#Check channel distribution:
df['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [34]:
#TASK 4: Build basic user journey view
df.groupby('User ID')['Channel'].apply(list).head()

User ID
10028                            [Display Ads, Search Ads]
10045                            [Display Ads, Search Ads]
10062                [Email, Direct Traffic, Social Media]
10068    [Social Media, Search Ads, Search Ads, Social ...
10095    [Email, Display Ads, Referral, Display Ads, Re...
Name: Channel, dtype: object

In [35]:
df['Channel'] = df['Channel'].fillna('Unknown')
df['Campaign'] = df['Campaign'].fillna('Unknown')

In [41]:
#User journey integrity check
df_cleaned.groupby('User ID').size().describe()

count    2847.000000
mean        3.512469
std         1.770702
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        12.000000
dtype: float64

In [43]:
#Timestamp sequence cheak
df_cleaned['Timestamp'] = pd.to_datetime(df_cleaned['Timestamp'])
df_cleaned.sort_values(['User ID', 'Timestamp'], inplace=True)

In [44]:
#Conversion sanity check
df_cleaned.groupby('User ID')['Conversion'].apply(lambda x: (x == 'Yes').any()).value_counts()

Conversion
True     2381
False     466
Name: count, dtype: int64

In [45]:
#Channel distribution check
df_cleaned['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64